### ISSUE TITLE
bot-test-app Crashed

### ISSUE THREAD

**Issue by nsand** [nsand/issues_dump#31]
`bot-test-app` crashed at **2016-05-31T14:51:14Z**
## Metadata
```
{"instance":"e4f5f6e18ae24dd9ad6767b4d63d2de4","index":1,"exit_status":1,"exit_description":"app instance exited","reason":"CRASHED"}
```
## Recent Logs
```
    at Timer.listOnTimeout (timers.js:92:15)
	^
Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
ReferenceError: some is not defined
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"bed824a8094044f28218d16b91d9c1c2", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464703235}
    at Timer.listOnTimeout (timers.js:92:15)
ReferenceError: some is not defined
    at Timer.listOnTimeout (timers.js:92:15)
	^
ReferenceError: some is not defined
	^
	^
    at Timer.listOnTimeout (timers.js:92:15)
	some.that.does.not.exist(0);
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"2be71df3cc644ff2a0d549880e61b112", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464703267}
    at crashIt (/home/vcap/app/app.js:11:2)
    at Timer.listOnTimeout (timers.js:92:15)
	some.that.does.not.exist(0);
ReferenceError: some is not defined
	^
	some.that.does.not.exist(0);
	^
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"24ade1d80ab044808d8fbb78634d9c50", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464704652}
    at Timer.listOnTimeout (timers.js:92:15)
    at crashIt (/home/vcap/app/app.js:11:2)
Starting app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
    at wrapper [as _onTimeout] (timers.js:275:11)
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"002ef30d3216436eb80af3f228375691", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464703952}
bot-test-app.mybluemix.net - [31/05/2016:14:20:09 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.154:30633 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:179f590f-f28e-4883-6956-5a36c596ea20 response_time:0.020108463 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"561409101"

bot-test-app.mybluemix.net - [31/05/2016:14:28:49 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.156:19897 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:746e5c39-b321-4bab-7800-f6357e1c20d9 response_time:0.031733843 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"3498616055"

    at wrapper [as _onTimeout] (timers.js:275:11)
	some.that.does.not.exist(0);
	some.that.does.not.exist(0);
	^
	^
ReferenceError: some is not defined
bot-test-app.mybluemix.net - [31/05/2016:14:25:55 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.154:18646 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:a68cc211-78da-4e33-5da3-9830231c0a3a response_time:0.037018613 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"846625519"

Starting app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
bot-test-app.mybluemix.net - [31/05/2016:14:23:34 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 192.155.237.116:33423 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:4fcb4dc5-d8b4-47c6-7e28-45125fcf03ca response_time:0.021635063 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"269778407"

App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"b1a597f0f858444cbef1389bd8802c11", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464704615}
bot-test-app.mybluemix.net - [31/05/2016:14:26:34 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.154:56900 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:fbded555-e9a8-42a5-7ae8-5f4085474008 response_time:0.02167463 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"900462857"

    at wrapper [as _onTimeout] (timers.js:275:11)
    at wrapper [as _onTimeout] (timers.js:275:11)
	some.that.does.not.exist(0);
```

**Comment by nsand** [comment]
`bot-test-app` crashed at **2016-05-31T14:56:11Z**
## Metadata
```
{"instance":"295207147e9f403eb37c034ea4c7c8c2","index":1,"exit_status":1,"exit_description":"app instance exited","reason":"CRASHED"}
```
## Recent Logs
```
	some.that.does.not.exist(0);
    at crashIt (/home/vcap/app/app.js:11:2)
ReferenceError: some is not defined
	some.that.does.not.exist(0);
Starting app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
ReferenceError: some is not defined
bot-test-app.mybluemix.net - [31/05/2016:14:14:39 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.155:19767 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:e65b428b-4b68-4247-7bde-d301de0a8555 response_time:0.16656142 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"2884776705"

App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"0fcb0f76c59043d894466e70439f1bc4", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464704755}
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"92a148e9231343e99213852100f51a96", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464704794}
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"f9e4b4ee897b42de9b331c02fe780926", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464704929}
Starting app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
Updated app with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed ({"state"=>"STARTED"})
    at crashIt (/home/vcap/app/app.js:11:2)
Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
ReferenceError: some is not defined
	some.that.does.not.exist(0);
    at crashIt (/home/vcap/app/app.js:11:2)
	some.that.does.not.exist(0);
ReferenceError: some is not defined
bot-test-app.mybluemix.net - [31/05/2016:13:53:52 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 192.155.237.118:52715 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:c7ac2331-2386-4c4d-6ae3-d80ede230156 response_time:0.078285514 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"4086955617"

    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
    at Timer.listOnTimeout (timers.js:92:15)
	some.that.does.not.exist(0);
ReferenceError: some is not defined
	some.that.does.not.exist(0);
	^
    at crashIt (/home/vcap/app/app.js:11:2)
Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
	^
ReferenceError: some is not defined
    at wrapper [as _onTimeout] (timers.js:275:11)
	some.that.does.not.exist(0);
    at wrapper [as _onTimeout] (timers.js:275:11)
Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"4b4db3586e0e4b8ba33a83c86d23662e", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464704079}
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
bot-test-app.mybluemix.net - [31/05/2016:14:00:35 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.155:13274 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:6d73c983-f012-4ddc-7f5f-d86f8e04b385 response_time:0.025013486 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"2665442879"

    at crashIt (/home/vcap/app/app.js:11:2)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
Starting app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"299e12b621704d7aa435e9ec1f9d878b", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464702832}
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
	^
```

**Comment by nsand** [comment]
`bot-test-app` crashed at **2016-05-31T14:56:11Z**
## Metadata
```
{"instance":"295207147e9f403eb37c034ea4c7c8c2","index":1,"exit_status":1,"exit_description":"app instance exited","reason":"CRASHED"}
```
## Recent Logs
```
Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
ReferenceError: some is not defined
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"299e12b621704d7aa435e9ec1f9d878b", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464702832}
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
	^
	some.that.does.not.exist(0);
	some.that.does.not.exist(0);
ReferenceError: some is not defined
	some.that.does.not.exist(0);
    at crashIt (/home/vcap/app/app.js:11:2)
    at Timer.listOnTimeout (timers.js:92:15)
	some.that.does.not.exist(0);
    at wrapper [as _onTimeout] (timers.js:275:11)
Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"4b4db3586e0e4b8ba33a83c86d23662e", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464704079}
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
    at Timer.listOnTimeout (timers.js:92:15)
ReferenceError: some is not defined
    at wrapper [as _onTimeout] (timers.js:275:11)
Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
    at crashIt (/home/vcap/app/app.js:11:2)
ReferenceError: some is not defined
    at crashIt (/home/vcap/app/app.js:11:2)
Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
ReferenceError: some is not defined
	some.that.does.not.exist(0);
    at crashIt (/home/vcap/app/app.js:11:2)
bot-test-app.mybluemix.net - [31/05/2016:14:28:49 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.156:19897 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:746e5c39-b321-4bab-7800-f6357e1c20d9 response_time:0.031733843 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"3498616055"

	^
    at Timer.listOnTimeout (timers.js:92:15)
    at crashIt (/home/vcap/app/app.js:11:2)
    at Timer.listOnTimeout (timers.js:92:15)
	^
    at crashIt (/home/vcap/app/app.js:11:2)
bot-test-app.mybluemix.net - [31/05/2016:14:19:01 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.156:60866 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:d857b516-8186-454d-63da-f3546bc9dc46 response_time:0.034228282 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"2885475201"

Starting app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
ReferenceError: some is not defined
ReferenceError: some is not defined
    at wrapper [as _onTimeout] (timers.js:275:11)
    at crashIt (/home/vcap/app/app.js:11:2)
	some.that.does.not.exist(0);
    at crashIt (/home/vcap/app/app.js:11:2)
    at Timer.listOnTimeout (timers.js:92:15)
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"8c4de1c065ba4deda7b54b38299b89c6", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464705299}
Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
    at crashIt (/home/vcap/app/app.js:11:2)
```

**Comment by nsand** [comment]
`bot-test-app` crashed at **2016-05-31T14:57:16Z**
## Metadata
```
{"instance":"60bc7939244047edb87da6dcdfe48722","index":0,"exit_status":1,"exit_description":"app instance exited","reason":"CRASHED"}
```
## Recent Logs
```
bot-test-app.mybluemix.net - [31/05/2016:14:20:09 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.154:30633 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:179f590f-f28e-4883-6956-5a36c596ea20 response_time:0.020108463 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"561409101"

bot-test-app.mybluemix.net - [31/05/2016:14:28:49 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.156:19897 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:746e5c39-b321-4bab-7800-f6357e1c20d9 response_time:0.031733843 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"3498616055"

App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"299e12b621704d7aa435e9ec1f9d878b", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464702832}
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
	^
bot-test-app.mybluemix.net - [31/05/2016:14:00:35 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.155:13274 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:6d73c983-f012-4ddc-7f5f-d86f8e04b385 response_time:0.025013486 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"2665442879"

    at crashIt (/home/vcap/app/app.js:11:2)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
Starting app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
	some.that.does.not.exist(0);
ReferenceError: some is not defined
	some.that.does.not.exist(0);
	^
	some.that.does.not.exist(0);
	^
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"24ade1d80ab044808d8fbb78634d9c50", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464704652}
    at Timer.listOnTimeout (timers.js:92:15)
    at crashIt (/home/vcap/app/app.js:11:2)
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"3385bc1a-2510-4dd2-9505-be4601f780e3", "instance"=>"295207147e9f403eb37c034ea4c7c8c2", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464706571}
	^
    at wrapper [as _onTimeout] (timers.js:275:11)
    at wrapper [as _onTimeout] (timers.js:275:11)
Updated app with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed ({"state"=>"STOPPED"})
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"1070f85f9d024ba18cd0f47c3e62cc48", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464704409}
App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"6a58bd1c-18e4-49e7-8d49-b150ca344c5f", "instance"=>"f6534eda31ca43b4844db03202c96e96", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464705093}
    at crashIt (/home/vcap/app/app.js:11:2)
	^
    at wrapper [as _onTimeout] (timers.js:275:11)
bot-test-app.mybluemix.net - [31/05/2016:14:51:14 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.154:35082 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:152f61d8-89d1-44a7-665f-8b34d435dcf1 response_time:0.02452954 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"853703007"

Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
	^
	^
	^
ReferenceError: some is not defined
bot-test-app.mybluemix.net - [31/05/2016:14:25:55 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.154:18646 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"http" vcap_request_id:a68cc211-78da-4e33-5da3-9830231c0a3a response_time:0.037018613 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"846625519"

Starting app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
    at crashIt (/home/vcap/app/app.js:11:2)
    at crashIt (/home/vcap/app/app.js:11:2)
Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
ReferenceError: some is not defined
	some.that.does.not.exist(0);
    at crashIt (/home/vcap/app/app.js:11:2)
	^
```
